### ISSUE TITLE
这个博客里的库哪儿去了

### ISSUE THREAD

**Issue by FanyangKong** [rsj217/flask--scaffold#1]
http://www.cnblogs.com/jsben/p/4909964.html

**Comment by rsj217** [comment]
那篇文章是很早之前写的，最早发布在 diandian.com 点点网，从内容也可以看出还是
SQLAlchemy==0.7.9时代。后来整理github也就顺手删掉了。

现在有更好的教程or书籍，例如 https://book.douban.com/subject/25814739/

不过，那个 cnblogs的博客不是我的，应该是他转载的吧。。。

2017-10-27 16:04 GMT+08:00 Alan <notifications@github.com>:

**Comment by FanyangKong** [comment]
最近在看python和建站，博客里面的代码不全源代码也找不到了很烦

**Comment by rsj217** [comment]
点点网的服务已经挂了，转到 简书 <http://www.jianshu.com/u/5qrPPM>了， 新博客
<http://blog.jiamin.info/>也不再收录旧的文记。

如果你想入门python 开发web，前文推荐的这本书 <https://item.jd.com/11594082.html>可以让你 one
step by step，开发一个应用。

博客里的教程其实也是那本书的学习笔记而已。

2017-10-28 15:02 GMT+08:00 Alan <notifications@github.com>:

**Comment by rsj217** [comment]
点点网的服务已经挂了，转到 简书  <http://www.jianshu.com/u/5qrPPM>了， 新博客
<http://blog.jiamin.info/>也不再收录旧的文记。

如果你想入门python 开发web，前文推荐的这本书 <https://item.jd.com/11594082.html>可以让你 one
step by step，开发一个应用。

博客里的教程其实也是那本书的学习笔记而已。

2017-10-27 16:04 GMT+08:00 Alan <notifications@github.com>:

**Comment by rsj217** [comment]
点点网的服务已经挂了，转到 简书  <http://www.jianshu.com/u/5qrPPM>了， 新博客
<http://blog.jiamin.info/>也不再收录旧的文记。

如果你想入门python 开发web，前文推荐的这本书 <https://item.jd.com/11594082.html>可以让你 one
step by step，开发一个应用。

博客里的教程其实也是那本书的学习笔记而已。

2017-10-28 14:43 GMT+08:00 Alan <notifications@github.com>:

**Comment by FanyangKong** [comment]
找到了那本书的电子版学习一下
